In [40]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

df=pd.read_csv("D:/인공지능개론/car_evaluation.csv", index_col=0)

label_encoder=LabelEncoder()
print("결측치 확인:")
print(df.isnull().sum())
#결측치 없음??


결측치 확인:
vhigh.1    0
2          0
2.1        0
small      0
low        0
unacc      0
dtype: int64


In [41]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)


X=df.iloc[:, :-1]
y=df.iloc[:, -1]

In [42]:
X = df_cleaned.iloc[:, :-1] 
y = df_cleaned.iloc[:, -1]   

# 데이터 분할 (80% 학습, 20% 테스트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

dt_clf=DecisionTreeClassifier()
rf_clf=RandomForestClassifier()
sv_clf=SVC()
lr_clf=LogisticRegression(max_iter=200)

dt_clf.fit(X_train, y_train)
dt_pred=dt_clf.predict(X_test)
print("Decision Tree Accuracy: {0:.4f}".format(accuracy_score(y_test, dt_pred)))

rf_clf.fit(X_train, y_train)
rf_pred=rf_clf.predict(X_test)
print("RandomForest Tree Accurcy: {0:.4f}".format(accuracy_score(y_test, rf_pred)))

sv_clf.fit(X_train, y_train)
sv_pred=sv_clf.predict(X_test)
print("SVM Accuracy: {0:.4f}".format(accuracy_score(y_test, sv_pred)))

lr_clf.fit(X_train, y_train)
lr_pred=lr_clf.predict(X_test)
print("Logistic Regression Accuracy: {0:.4f}".format(accuracy_score(y_test, lr_pred)))

Decision Tree Accuracy: 0.7283
RandomForest Tree Accurcy: 0.7225
SVM Accuracy: 0.7832
Logistic Regression Accuracy: 0.6821


In [43]:
#예측값과 실제 결과 비교
comparison_df=pd.DataFrame({
    "Actual": y_test.values,
    "DecisionTree": dt_pred,
    "RandomForest": rf_pred,
    "SVM": sv_pred,
    "LogisticRegression": lr_pred
})

#상위 10개만 비교하기
print(comparison_df.head(10))

   Actual  DecisionTree  RandomForest  SVM  LogisticRegression
0       2             2             2    2                   2
1       2             2             2    2                   2
2       2             2             2    2                   2
3       0             0             0    0                   2
4       2             2             2    2                   0
5       0             2             2    2                   2
6       2             2             2    2                   2
7       2             2             2    2                   2
8       2             2             2    2                   2
9       2             2             2    2                   2


In [44]:
#KNN 모델 생성 (k=3)
k=3
knn=KNeighborsClassifier(n_neighbors=k)

#모델 학습
knn.fit(X_train, y_train)

y_pred=knn.predict(X_test)
accuracy=accuracy_score(y_test, y_pred)
knn_cm=confusion_matrix(y_test, y_pred)

print(f"KNN accuracy: {accuracy:.4f}")
print("KNN Confusion Matrix:\n", knn_cm)

KNN accuracy: 0.7197
KNN Confusion Matrix:
 [[ 35   6  30   6]
 [ 14   1   0   0]
 [ 24   0 213   0]
 [ 17   0   0   0]]


In [45]:
dt_clf=DecisionTreeClassifier()
rf_clf=RandomForestClassifier()
sv_clf=SVC()
lr_clf=LogisticRegression(max_iter=200)

dt_clf.fit(X_train, y_train)
dt_pred=dt_clf.predict(X_test)
dt_cm=confusion_matrix(y_test, dt_pred)

print("Decision Tree Accuracy: {0:.4f}".format(accuracy_score(y_test, dt_pred)))
print("Decision Tree Confusion Matrix:\n", dt_cm)

Decision Tree Accuracy: 0.7283
Decision Tree Confusion Matrix:
 [[ 41   5  25   6]
 [ 15   0   0   0]
 [ 26   0 211   0]
 [ 16   0   1   0]]


In [46]:
rf_clf.fit(X_train, y_train)
rf_pred=rf_clf.predict(X_test)
rf_cm=confusion_matrix(y_test, rf_pred)

print("RandomForest Tree Accurcy: {0:.4f}".format(accuracy_score(y_test, rf_pred)))
print("RandomForest Tree Confusion Matrix:\n", rf_cm)

RandomForest Tree Accurcy: 0.7197
RandomForest Tree Confusion Matrix:
 [[ 31   6  33   7]
 [ 14   1   0   0]
 [ 21   0 216   0]
 [ 15   0   1   1]]


In [47]:
sv_clf.fit(X_train, y_train)
sv_pred=sv_clf.predict(X_test)
sv_cm=confusion_matrix(y_test, sv_pred)

print("SVM Accuracy: {0:.4f}".format(accuracy_score(y_test, sv_pred)))
print("SVM Confusion Matrix:\n", sv_cm)

SVM Accuracy: 0.7832
SVM Confusion Matrix:
 [[ 49   0  28   0]
 [ 15   0   0   0]
 [ 15   0 222   0]
 [ 17   0   0   0]]


In [48]:
lr_clf.fit(X_train, y_train)
lr_pred=lr_clf.predict(X_test)
lr_cm=confusion_matrix(y_test, lr_pred)

print("Logistic Regression Accuracy: {0:.4f}".format(accuracy_score(y_test, lr_pred)))
print("Logistic Regression Confusion Matrix:\n", lr_cm)

Logistic Regression Accuracy: 0.6821
Logistic Regression Confusion Matrix:
 [[ 13   0  63   1]
 [  3   0  12   0]
 [ 15   0 222   0]
 [ 11   0   5   1]]
