In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
df=pd.read_csv("/content/drive/MyDrive/car_evaluation.csv", header=None)
df

0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [12]:
df.columns=['price','maint', 'doors', 'persons', 'lug_capacity', 'safety', 'output' ]

In [13]:
df


price  maint  doors persons lug_capacity safety output
0     vhigh  vhigh      2       2        small    low  unacc
1     vhigh  vhigh      2       2        small    med  unacc
2     vhigh  vhigh      2       2        small   high  unacc
3     vhigh  vhigh      2       2          med    low  unacc
4     vhigh  vhigh      2       2          med    med  unacc
...     ...    ...    ...     ...          ...    ...    ...
1723    low    low  5more    more          med    med   good
1724    low    low  5more    more          med   high  vgood
1725    low    low  5more    more          big    low  unacc
1726    low    low  5more    more          big    med   good
1727    low    low  5more    more          big   high  vgood

[1728 rows x 7 columns]

In [15]:
df.isnull().sum()

price           0
maint           0
doors           0
persons         0
lug_capacity    0
safety          0
output          0
dtype: int64

In [25]:
label_encodes={} #모든 값을 숫자로 인코딩하기
for col in df.columns:
  label_encodes[col]=LabelEncoder()
  df[col]=label_encodes[col].fit_transform(df[col])

In [26]:
df

price  maint  doors  persons  lug_capacity  safety  output
0         3      3      0        0             2       1       2
1         3      3      0        0             2       2       2
2         3      3      0        0             2       0       2
3         3      3      0        0             1       1       2
4         3      3      0        0             1       2       2
...     ...    ...    ...      ...           ...     ...     ...
1723      1      1      3        2             1       2       1
1724      1      1      3        2             1       0       3
1725      1      1      3        2             0       1       2
1726      1      1      3        2             0       2       1
1727      1      1      3        2             0       0       3

[1728 rows x 7 columns]

In [27]:
df['output'].value_counts()

output
2    1210
0     384
1      69
3      65
Name: count, dtype: int64

In [28]:
X=df.drop('output', axis=1).values
y=df['output'].values

In [29]:
X

array([[3, 3, 0, 0, 2, 1],
       [3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       ...,
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]])

In [30]:
y

array([2, 2, 2, ..., 2, 1, 3])

In [34]:

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=0)

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [35]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1382, 6), (346, 6), (1382,), (346,))

In [36]:
dt_clf=DecisionTreeClassifier()
rf_clf=RandomForestClassifier()
sv_clf=SVC()
lr_clf=LogisticRegression(max_iter=200)

dt_clf.fit(X_train, y_train)
dt_pred=dt_clf.predict(X_test)
print("Decision Tree Accuracy: {0:.4f}".format(accuracy_score(y_test, dt_pred)))

rf_clf.fit(X_train, y_train)
rf_pred=rf_clf.predict(X_test)
print("RandomForest Tree Accurcy: {0:.4f}".format(accuracy_score(y_test, rf_pred)))

sv_clf.fit(X_train, y_train)
sv_pred=sv_clf.predict(X_test)
print("SVM Accuracy: {0:.4f}".format(accuracy_score(y_test, sv_pred)))

lr_clf.fit(X_train, y_train)
lr_pred=lr_clf.predict(X_test)
print("Logistic Regression Accuracy: {0:.4f}".format(accuracy_score(y_test, lr_pred)))

Decision Tree Accuracy: 0.9798
RandomForest Tree Accurcy: 0.9711
SVM Accuracy: 0.9191
Logistic Regression Accuracy: 0.6503


In [37]:
#KNN 모델 생성 (k=3)
k=3
knn=KNeighborsClassifier(n_neighbors=k)

#모델 학습
knn.fit(X_train, y_train)

y_pred=knn.predict(X_test)
accuracy=accuracy_score(y_test, y_pred)
knn_cm=confusion_matrix(y_test, y_pred)

print(f"KNN accuracy: {accuracy:.4f}")
print("KNN Confusion Matrix:\n", knn_cm)

KNN accuracy: 0.9249
KNN Confusion Matrix:
 [[ 73   2   4   0]
 [  6  11   0   0]
 [ 10   0 230   0]
 [  4   0   0   6]]


In [38]:
dt_clf=DecisionTreeClassifier()
rf_clf=RandomForestClassifier()
sv_clf=SVC()
lr_clf=LogisticRegression(max_iter=200)

dt_clf.fit(X_train, y_train)
dt_pred=dt_clf.predict(X_test)
dt_cm=confusion_matrix(y_test, dt_pred)

print("Decision Tree Accuracy: {0:.4f}".format(accuracy_score(y_test, dt_pred)))
print("Decision Tree Confusion Matrix:\n", dt_cm)

Decision Tree Accuracy: 0.9798
Decision Tree Confusion Matrix:
 [[ 74   2   3   0]
 [  0  17   0   0]
 [  1   0 239   0]
 [  1   0   0   9]]


In [39]:
rf_clf.fit(X_train, y_train)
rf_pred=rf_clf.predict(X_test)
rf_cm=confusion_matrix(y_test, rf_pred)

print("RandomForest Tree Accurcy: {0:.4f}".format(accuracy_score(y_test, rf_pred)))
print("RandomForest Tree Confusion Matrix:\n", rf_cm)

RandomForest Tree Accurcy: 0.9740
RandomForest Tree Confusion Matrix:
 [[ 75   2   1   1]
 [  1  16   0   0]
 [  3   0 237   0]
 [  1   0   0   9]]


In [40]:
sv_clf.fit(X_train, y_train)
sv_pred=sv_clf.predict(X_test)
sv_cm=confusion_matrix(y_test, sv_pred)

print("SVM Accuracy: {0:.4f}".format(accuracy_score(y_test, sv_pred)))
print("SVM Confusion Matrix:\n", sv_cm)

SVM Accuracy: 0.9191
SVM Confusion Matrix:
 [[ 75   0   3   1]
 [  7   8   0   2]
 [ 12   0 228   0]
 [  3   0   0   7]]


In [41]:
lr_clf.fit(X_train, y_train)
lr_pred=lr_clf.predict(X_test)
lr_cm=confusion_matrix(y_test, lr_pred)

print("Logistic Regression Accuracy: {0:.4f}".format(accuracy_score(y_test, lr_pred)))
print("Logistic Regression Confusion Matrix:\n", lr_cm)

Logistic Regression Accuracy: 0.6503
Logistic Regression Confusion Matrix:
 [[  9   0  67   3]
 [  1   0  16   0]
 [ 22   0 214   4]
 [  2   0   6   2]]
