In [68]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

#데이터 로딩기기
df = pd.read_csv("D:/인공지능개론/titanic.csv", index_col=0)

#결측치 확인하기 
print("결측치 확인:")
print(df.isnull().sum())

#변환 전
print(df['Survived'].value_counts())

#LabeEncoder
label_encoder=LabelEncoder()

#컬럼 삭제
df.drop(columns=['Ticket', 'Cabin', 'Name', 'Embarked'], inplace=True)

#결측치 평균값으로 채우기
df['Age']=df['Age'].fillna(df['Age'].mean())
df

결측치 확인:
Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64
Survived
0    549
1    342
Name: count, dtype: int64


Survived  Pclass     Sex        Age  SibSp  Parch     Fare
PassengerId                                                            
1                   0       3    male  22.000000      1      0   7.2500
2                   1       1  female  38.000000      1      0  71.2833
3                   1       3  female  26.000000      0      0   7.9250
4                   1       1  female  35.000000      1      0  53.1000
5                   0       3    male  35.000000      0      0   8.0500
...               ...     ...     ...        ...    ...    ...      ...
887                 0       2    male  27.000000      0      0  13.0000
888                 1       1  female  19.000000      0      0  30.0000
889                 0       3  female  29.699118      1      2  23.4500
890                 1       1    male  26.000000      0      0  30.0000
891                 0       3    male  32.000000      0      0   7.7500

[891 rows x 7 columns]

In [69]:
#결측치 확인
df.isnull().sum()

#엔코딩
df['Sex']=LabelEncoder().fit_transform(df['Sex'])

#변환 후
print(df['Survived'].value_counts())
X=df.drop(columns=['Survived'])
y=df['Survived']

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)


Survived
0    549
1    342
Name: count, dtype: int64


In [71]:
#KNN 모델 생성 (k=3)
k=3
knn=KNeighborsClassifier(n_neighbors=k)

#모델 학습
knn.fit(X_train, y_train)

y_pred=knn.predict(X_test)
accuracy=accuracy_score(y_test, y_pred)
knn_cm=confusion_matrix(y_test, y_pred)

print(f"KNN accuracy: {accuracy:.4f}")
print("KNN Confusion Matrix:\n", knn_cm)

KNN accuracy: 0.8101
KNN Confusion Matrix:
 [[89 16]
 [18 56]]


In [73]:
dt_clf=DecisionTreeClassifier()
rf_clf=RandomForestClassifier()
sv_clf=SVC()
lr_clf=LogisticRegression(max_iter=200)

dt_clf.fit(X_train, y_train)
dt_pred=dt_clf.predict(X_test)
dt_cm=confusion_matrix(y_test, dt_pred)

print("Decision Tree Accuracy: {0:.4f}".format(accuracy_score(y_test, dt_pred)))
print("Decision Tree Confusion Matrix:\n", dt_cm)

Decision Tree Accuracy: 0.7430
Decision Tree Confusion Matrix:
 [[82 23]
 [23 51]]


In [74]:
rf_clf.fit(X_train, y_train)
rf_pred=rf_clf.predict(X_test)
rf_cm=confusion_matrix(y_test, rf_pred)

print("RandomForest Tree Accurcy: {0:.4f}".format(accuracy_score(y_test, rf_pred)))
print("RandomForest Tree Confusion Matrix:\n", rf_cm)

RandomForest Tree Accurcy: 0.8045
RandomForest Tree Confusion Matrix:
 [[90 15]
 [20 54]]


In [76]:
sv_clf.fit(X_train, y_train)
sv_pred=sv_clf.predict(X_test)
sv_cm=confusion_matrix(y_test, sv_pred)

print("SVM Accuracy: {0:.4f}".format(accuracy_score(y_test, sv_pred)))
print("SVM Confusion Matrix:\n", sv_cm)

SVM Accuracy: 0.8101
SVM Confusion Matrix:
 [[92 13]
 [21 53]]


In [77]:
lr_clf.fit(X_train, y_train)
lr_pred=lr_clf.predict(X_test)
lr_cm=confusion_matrix(y_test, lr_pred)

print("Logistic Regression Accuracy: {0:.4f}".format(accuracy_score(y_test, lr_pred)))
print("Logistic Regression Confusion Matrix:\n", lr_cm)

Logistic Regression Accuracy: 0.7989
Logistic Regression Confusion Matrix:
 [[90 15]
 [21 53]]
