In [19]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split

df=pd.read_csv("D:/인공지능개론/kc_house_data.csv")

df

id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242     2.0           0     0  ...      7   
2              770     10000     1.0           0     0  ...      6   
3             1960      5000     1.0           0     0  ...      7   
4             1680      8080     1.0           0     0  ...      8   
...            ...       ...     ...         ...   ...  ...    ...   
21608         1530      1131     3.0           0     0  ...      8   
21609         2310      5813     2.0           0     0  ...      8   
21610         1020      1350     2.0           0     0  ...      7   
21611         1600      2388     2.0           0     0  ...      8   
21612         1020      1076     2.0           0     0  ...      7   

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112   
1            2170            400      1951          1991    98125  47.7210   
2             770              0      1933             0    98028  47.7379   
3            1050            910      1965             0    98136  47.5208   
4            1680              0      1987             0    98074  47.6168   
...           ...            ...       ...           ...      ...      ...   
21608        1530              0      2009             0    98103  47.6993   
21609        2310              0      2014             0    98146  47.5107   
21610        1020              0      2009             0    98144  47.5944   
21611        1600              0      2004             0    98027  47.5345   
21612        1020              0      2008             0    98144  47.5941   

          long  sqft_living15  sqft_lot15  
0     -122.257           1340        5650  
1     -122.319           1690        7639  
2     -122.233           2720        8062  
3     -122.393           1360        5000  
4     -122.045           1800        7503  
...        ...            ...         ...  
21608 -122.346           1530        1509  
21609 -122.362           1830        7200  
21610 -122.299           1020        2007  
21611 -122.069           1410        1287  
21612 -122.299           1020        1357  

[21613 rows x 21 columns]

In [20]:
label_encoder=LabelEncoder()

In [21]:
print("결측치 확인:")
print(df.isnull().sum())

결측치 확인:
id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64


In [22]:
#결측치 없음

In [16]:
scaler=StandardScaler()

In [35]:
label_encodes={} #모든 값을 숫자로 인코딩하기
for col in df.columns:
  label_encodes[col]=LabelEncoder()
  df[col]=label_encodes[col].fit_transform(df[col])

In [36]:
X=df.drop(columns=['grade'])
y=df['grade']

In [37]:

X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=0)

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [38]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17290, 20) (17290,)
(4323, 20) (4323,)


In [39]:

dt_clf=DecisionTreeClassifier()
rf_clf=RandomForestClassifier()
sv_clf=SVC()
lr_clf=LogisticRegression(max_iter=200)

dt_clf.fit(X_train, y_train)
dt_pred=dt_clf.predict(X_test)
print("Decision Tree Accuracy: {0:.4f}".format(accuracy_score(y_test, dt_pred)))

rf_clf.fit(X_train, y_train)
rf_pred=rf_clf.predict(X_test)
print("RandomForest Tree Accurcy: {0:.4f}".format(accuracy_score(y_test, rf_pred)))

sv_clf.fit(X_train, y_train)
sv_pred=sv_clf.predict(X_test)
print("SVM Accuracy: {0:.4f}".format(accuracy_score(y_test, sv_pred)))

lr_clf.fit(X_train, y_train)
lr_pred=lr_clf.predict(X_test)
print("Logistic Regression Accuracy: {0:.4f}".format(accuracy_score(y_test, lr_pred)))

Decision Tree Accuracy: 0.6169
RandomForest Tree Accurcy: 0.7236
SVM Accuracy: 0.6852
Logistic Regression Accuracy: 0.6570


D:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [40]:

#KNN 모델 생성 (k=3)
k=3
knn=KNeighborsClassifier(n_neighbors=k)

#모델 학습
knn.fit(X_train, y_train)

y_pred=knn.predict(X_test)
accuracy=accuracy_score(y_test, y_pred)
knn_cm=confusion_matrix(y_test, y_pred)

print(f"KNN accuracy: {accuracy:.4f}")
print("KNN Confusion Matrix:\n", knn_cm)

KNN accuracy: 0.6241
KNN Confusion Matrix:
 [[   0    4    2    0    0    0    0    0    0    0]
 [   3    7   20   16    0    0    0    0    0    0]
 [   2   24  174  213    2    0    0    0    0    0]
 [   0    5  133 1459  233   12    1    1    0    0]
 [   0    0   20  347  671  110    8    2    0    0]
 [   0    0    0   43  163  266   44    8    1    0]
 [   0    0    0    5   41   85   94   11    2    0]
 [   0    0    0    0    6   14   23   24    1    0]
 [   0    0    0    0    0    3    5   11    3    0]
 [   0    0    0    0    0    0    1    0    0    0]]
